### ISSUE TITLE
Error Type Any, expected Number.

### ISSUE THREAD

**Issue by azhizhinov** [secondcoming/a3_exile_occupation#2]
Hello!

Sorry for bothering you, but sometime spawn fails.

This log from Napf Island A3.

20:18:55 "<infiSTAR.de>A3_EXILE_OCCUPATION| [OCCUPATION:Vehicle] bandit vehicle Exile_Car_Hunter spawned @ [any,11057.5,0]   [09-Apr-2016 18-33-27 - v0045]"

Somewhere around this code you need to check !=any, maybe?
		// Get position of nearest roads
		_nearRoads = _pos nearRoads 500;
		_nearestRoad = _nearRoads select 0;
		_nearestRoad = position (_nearRoads select 0);
		_spawnLocation = [_nearestRoad select 0, _pos select 1, 0];

_nearestRoad = _nearRoads select 0; not need at all?

Maybe there are no roads within 500?

Sorry for my English and Good Luck.

**Comment by secondcoming** [comment]
I'll have a look, thanks for letting me know :+1:

**Comment by secondcoming** [comment]
I will increase the range check for roads to 2000m in the next release and it should reduce the frequency of errors
