### ISSUE TITLE
Game keypress / Blackscreen

### ISSUE THREAD

**Issue by alexandre-leites** [secondcoming/a3_exile_occupation#5]
Hello,

I'do like to report a random error which occurs in the latest version of your mod. I get at random rates a blackscreen without the possibility of controlling anything in the game after getting out of a vehicle and I'm not able to control the camera when I'm inside the vehicle.

**Comment by secondcoming** [comment]
I've not heard of anything like this and nothing the mod controls would have any impact on player when they are inside vehicles.
